apiVersion: v1
kind: Service
metadata:
  name: immich-public-proxy
  namespace: ${NAMESPACE}
  labels:
    app: immich-public-proxy
spec:
  type: ClusterIP
  selector:
    app: immich-public-proxy
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
